openapi: "3.0.3"
info:
  version: 1.0.0
  title: Simple Goods Api
paths:
  /good-list:
    get:
      summary: List all goods
      operationId: listGoods
      tags:
        - Goods
      responses:
        '200':
          description: A List of Goods
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GoodsList"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    GoodsList:
      type: array
      items:
        $ref: "#/components/schemas/Good"

    Good:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        priority:
          type: integer

    Error:
      required:
        - errorCode
        - additionalInformation
      properties:
        errorCode:
          type: string
        additionalInformation:
          type: string