apiVersion: v1
kind: Service
metadata:
  labels:
    app: goods-service
  name: goods-service
spec:
  type: LoadBalancer
  ports:
    - port: 8040
      protocol: TCP
  selector:
    app: goods-service